(* ::Package:: *)

(* ::Input:: *)
(*(*Package for putting polynomial coefficients*)*)
(*BeginPackage["FinalCoef`"]*)
(**)
(*FinalCoef::usage=*)
(*"FinalCoef[p] returns a polynomial with coefficients between [-q/2,q/2] instead of [0,q-1]"*)
(*Begin["`Private`"]*)
(*FinalCoef[p_,n_,q_]*)
(*for i:1:n*)
(*if p[[i]]==0*)
(*	FinalCoef[[i]]=0*)
(*else*)
(*	if p[[i]]>q/2*)
(*		FinalCoef[[i]]=p[[i]]-q*)
(*	else*)
(*		FinalCoef[[i]]=p[[i]]-q*)
(**)
(*End[]*)
(*EndPackage[]*)
