(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage["Package`"]*)
(**)
(*MyFunction::usage="MainFunction[ x] computes a simple function."*)
(**)
(*Begin["Private`"]*)
(**)
(*MyFunction[x_]:=Module[{y},y=x^2;*)
(*y+1]*)
(**)
(*End[]*)
(**)
(*EndPackage[]*)
